In [1]:
import os
import numpy as np
import pandas as pd

In [43]:
os.chdir('/home/shreya/DEAP/CNN/TaskValence/HighValence')
high= []
high = [[] for ind in range(33)]
for file in os.listdir('/home/shreya/DEAP/CNN/TaskValence/HighValence'):
    if(file[0] == 's'):
#         print(file)
        subject = file[1:3]
#         print(subject)
        if subject[0] == '0':
            subj_no = int(subject[1])
        else:
            subj_no = int(subject)
#         print(type(subj_no))
        trial = file[4:6]
#         print(trial)
        if trial[1] == '_':
            trial_no = int(trial[0])
        else:
            trial_no = int(trial)
#         print(type(trial_no))
        high[subj_no].append(trial_no)
#         break

In [44]:
os.chdir('/home/shreya/DEAP/CNN/TaskValence/LowValence')
low= []
low = [[] for ind in range(33)]
for file in os.listdir('/home/shreya/DEAP/CNN/TaskValence/LowValence'):
    if(file[0] == 's'):
#         print(file)
        subject = file[1:3]
#         print(subject)
        if subject[0] == '0':
            subj_no = int(subject[1])
        else:
            subj_no = int(subject)
#         print(type(subj_no))
        trial = file[4:6]
#         print(trial)
        if trial[1] == '_':
            trial_no = int(trial[0])
        else:
            trial_no = int(trial)
#         print(type(trial_no))
        low[subj_no].append(trial_no)
#         break

In [45]:
os.chdir('/home/shreya/DEAP/CNN/TaskValence/NoneValence')
none= []
none = [[] for ind in range(33)]
for file in os.listdir('/home/shreya/DEAP/CNN/TaskValence/NoneValence'):
    if(file[0] == 's'):
#         print(file)
        subject = file[1:3]
#         print(subject)
        if subject[0] == '0':
            subj_no = int(subject[1])
        else:
            subj_no = int(subject)
#         print(type(subj_no))
        trial = file[4:6]
#         print(trial)
        if trial[1] == '_':
            trial_no = int(trial[0])
        else:
            trial_no = int(trial)
#         print(type(trial_no))
        none[subj_no].append(trial_no)
#         break

In [46]:
high = [ list(set(trial_list)) for trial_list in high]
low = [ list(set(trial_list)) for trial_list in low]
none = [ list(set(trial_list)) for trial_list in none]

In [47]:
df_trials = pd.DataFrame(list(zip(high, low, none)), columns =['High', 'Low', 'None'])

In [48]:
df_trials

,High,Low,None
0,[],[],[]
1,"[0, 1, 2, 4, 5, 6, 7, 15, 17, 18, 19, 20, 21, ...","[32, 33, 34, 35, 36, 37, 38, 8, 9, 10, 11, 12,...","[3, 39]"
2,"[0, 1, 2, 3, 39, 8, 7, 10, 11, 12, 13, 14, 15,...","[34, 36, 37, 38, 20, 22, 27, 28, 29, 30, 31]","[32, 33, 35, 4, 5, 6, 9, 21, 26]"
3,"[0, 1, 2, 4, 5, 6, 7, 8, 39, 10, 11, 12, 13, 1...","[32, 33, 34, 3, 37, 38, 9, 16, 22, 23, 24, 25,...","[35, 36, 20, 21, 31]"
4,"[0, 2, 3, 7, 8, 10, 13, 14, 16, 18, 19, 24, 25...","[1, 4, 6, 9, 12, 15, 20, 21, 22, 23, 27, 28, 2...","[17, 11, 5]"
5,"[0, 1, 3, 5, 7, 8, 10, 11, 13, 14, 15, 16, 17,...","[36, 37, 38, 4, 9, 20, 22, 23, 27, 28, 29, 31]","[32, 2, 35, 34, 6, 12]"
6,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14,...","[33, 34, 37, 22, 23, 28, 30]","[36, 39, 10, 15, 19, 25, 26]"
7,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[33, 15, 20, 21, 22, 23, 24, 25, 27, 29]","[32, 34, 36, 37, 31]"
8,"[0, 2, 3, 5, 7, 8, 10, 11, 12, 13, 14, 16, 17,...","[32, 34, 35, 4, 37, 39, 15, 20, 21, 22, 23, 24...","[1, 33, 36, 38, 6, 9, 18, 25, 27]"
9,"[1, 2, 3, 5, 7, 8, 10, 11, 12, 13, 14, 16, 30]","[32, 34, 35, 36, 37, 38, 9, 15, 18, 20, 21, 23...","[0, 33, 4, 6, 39, 17, 19, 22, 24, 26]"
10,"[0, 2, 3, 4, 5, 6, 39, 8, 9, 10, 7, 11, 13, 14...","[33, 34, 35, 36, 37, 38, 1, 15, 20, 21, 22, 24...","[32, 25, 26, 16]"
11,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14,...","[34, 35, 36, 37, 38, 15, 20, 22, 23, 26, 27, 2...","[33, 39, 11, 24, 31]"
12,"[0, 1, 2, 3, 5, 6, 39, 8, 10, 11, 12, 13, 14, ...","[32, 34, 35, 4, 37, 38, 36, 9, 20, 21, 22, 23,...","[33, 7, 15, 16, 26, 27]"
13,"[0, 2, 3, 7, 8, 10, 12, 13, 16, 17, 18, 19, 26...","[1, 5, 6, 9, 20, 21, 22, 23, 24, 28, 29, 30, 3...","[4, 11, 14, 15, 25]"
14,"[0, 1, 2, 3, 5, 38, 6, 8, 7, 10, 11, 12, 13, 1...","[32, 33, 34, 35, 36, 4, 37, 9, 15, 20, 21, 22,...",[]
15,"[0, 2, 3, 4, 5, 7, 8, 10, 11, 12, 13, 14, 16, ...","[32, 33, 35, 36, 37, 38, 39, 15, 20, 21, 22, 2...","[1, 34, 6, 9, 25]"
16,"[1, 2, 3, 36, 4, 38, 6, 10, 11, 17, 21, 29]","[0, 7, 8, 12, 13, 14, 16, 18, 19, 20, 22, 23, ...","[35, 5, 9, 15, 31]"
17,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15...","[32, 0, 34, 35, 36, 37, 12, 16, 20, 21, 22, 23...","[33, 39]"
18,"[0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14...","[32, 33, 36, 37, 38, 15, 20, 22, 23, 24, 29, 3...","[34, 28, 7, 39]"
19,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14...","[32, 33, 34, 35, 36, 37, 39, 15, 20, 22, 23, 2...","[38, 9, 21, 25, 26, 30, 31]"
20,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14...","[32, 33, 34, 35, 36, 37, 38, 21, 22, 23, 24, 2...","[39, 9, 15, 16, 20, 26, 27]"
21,"[0, 1, 32, 35, 4, 5, 38, 7, 8, 6, 10, 9, 13, 1...","[33, 36, 37, 39, 11, 12, 19, 20, 21, 22, 23, 2...","[2, 34, 3, 30]"
22,"[1, 2, 3, 4, 6, 7, 8, 10, 12, 13, 15, 17, 18, ...","[32, 34, 35, 36, 37, 38, 39, 9, 20, 21, 22, 23...","[0, 33, 5, 11, 14, 16, 25]"
23,"[0, 1, 2, 33, 3, 4, 6, 7, 8, 10, 11, 12, 13, 1...","[36, 16, 19, 20, 21, 22, 28, 29]","[32, 34, 35, 5, 38, 39, 37, 9, 15, 24, 26, 27,..."
24,"[0, 1, 2, 3, 4, 5, 7, 8, 10, 11, 12, 13, 14, 1...","[6, 15, 16, 19, 20, 21, 22, 23, 24, 25, 27, 28...","[32, 9, 39]"
25,"[0, 2, 6, 7, 8, 10, 11, 12, 13, 14, 15, 18, 19...","[32, 1, 34, 35, 36, 37, 38, 39, 9, 17, 22, 23,...","[33, 3, 4, 5, 16, 24, 25, 26, 27]"
26,"[0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 14, 1...","[32, 33, 34, 35, 4, 36, 38, 39, 37, 9, 22, 30,...","[16, 25, 29]"
27,"[0, 1, 2, 3, 5, 7, 8, 9, 10, 12, 13, 15, 16, 1...","[33, 34, 36, 37, 38, 11, 24]","[32, 4, 6, 39, 14, 18, 25, 26, 27, 30, 31]"
28,"[0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 15, 16...","[34, 35, 36, 37, 38, 12, 20, 22, 23, 24, 25, 2...","[8, 21, 14]"
29,"[0, 1, 2, 3, 4, 5, 6, 38, 39, 8, 10, 11, 12, 1...","[32, 33, 34, 37, 14, 15, 20, 21, 22, 23, 24, 2...","[16, 35, 36]"
30,"[1, 2, 3, 4, 5, 7, 8, 10, 16, 17, 18, 19, 23, ...","[32, 35, 36, 6, 38, 12, 20, 21, 22, 24, 29, 30]","[0, 33, 34, 37, 39, 9, 11, 13, 14, 15, 25, 27,..."
31,"[0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13, 14, 15, ...","[32, 33, 34, 36, 37, 38, 39, 9, 22, 29, 31]","[1, 35, 5, 16, 20, 21, 23, 26, 27, 28, 30]"
32,"[0, 2, 3, 4, 5, 7, 8, 39, 10, 11, 12, 13, 16, ...","[32, 33, 34, 35, 36, 37, 38, 9, 15, 20, 21, 22...","[25, 1, 14, 6]"

In [49]:
high_nb = [ len(trial_list) for trial_list in high]
low_nb = [ len(trial_list) for trial_list in low]
none_nb= [ len(trial_list) for trial_list in none]

In [50]:
df_nb = pd.DataFrame(list(zip(high_nb, low_nb, none_nb)), columns =['High', 'Low', 'None'])

In [52]:
os.chdir('/home/shreya/DEAP/CNN')
df_nb.to_csv('Tv.csv')

In [53]:
df_nb.to_csv('TV.csv')

In [54]:
os.chdir('/home/shreya/DEAP/CNN/TaskArousal/HighArousal')
high= []
high = [[] for ind in range(33)]
for file in os.listdir('/home/shreya/DEAP/CNN/TaskArousal/HighArousal'):
    if(file[0] == 's'):
#         print(file)
        subject = file[1:3]
#         print(subject)
        if subject[0] == '0':
            subj_no = int(subject[1])
        else:
            subj_no = int(subject)
#         print(type(subj_no))
        trial = file[4:6]
#         print(trial)
        if trial[1] == '_':
            trial_no = int(trial[0])
        else:
            trial_no = int(trial)
#         print(type(trial_no))
        high[subj_no].append(trial_no)
#         break

In [55]:
os.chdir('/home/shreya/DEAP/CNN/TaskArousal/LowArousal')
low= []
low = [[] for ind in range(33)]
for file in os.listdir('/home/shreya/DEAP/CNN/TaskArousal/LowArousal'):
    if(file[0] == 's'):
#         print(file)
        subject = file[1:3]
#         print(subject)
        if subject[0] == '0':
            subj_no = int(subject[1])
        else:
            subj_no = int(subject)
#         print(type(subj_no))
        trial = file[4:6]
#         print(trial)
        if trial[1] == '_':
            trial_no = int(trial[0])
        else:
            trial_no = int(trial)
#         print(type(trial_no))
        low[subj_no].append(trial_no)
#         break

In [56]:
os.chdir('/home/shreya/DEAP/CNN/TaskArousal/NoneArousal')
none= []
none = [[] for ind in range(33)]
for file in os.listdir('/home/shreya/DEAP/CNN/TaskArousal/NoneArousal'):
    if(file[0] == 's'):
#         print(file)
        subject = file[1:3]
#         print(subject)
        if subject[0] == '0':
            subj_no = int(subject[1])
        else:
            subj_no = int(subject)
#         print(type(subj_no))
        trial = file[4:6]
#         print(trial)
        if trial[1] == '_':
            trial_no = int(trial[0])
        else:
            trial_no = int(trial)
#         print(type(trial_no))
        none[subj_no].append(trial_no)
#         break

In [57]:
high = [ list(set(trial_list)) for trial_list in high]
low = [ list(set(trial_list)) for trial_list in low]
none = [ list(set(trial_list)) for trial_list in none]

In [58]:
df_trials = pd.DataFrame(list(zip(high, low, none)), columns =['High', 'Low', 'None'])

In [59]:
df_trials

,High,Low,None
0,[],[],[]
1,"[0, 1, 2, 3, 14, 15, 16, 17, 18, 19, 20, 23, 2...","[32, 4, 5, 6, 7, 8, 10, 11, 12, 13, 21, 22, 27...",[9]
2,"[1, 2, 7, 8, 11, 13, 14, 17, 18, 19, 23, 24, 2...","[33, 34, 3, 4, 35, 38, 6, 9, 10, 16, 20, 21, 22]","[0, 5, 12, 15, 26, 27]"
3,"[33, 35, 36, 37, 38, 9, 20]","[0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14...",[34]
4,"[2, 10, 13, 14, 16, 18, 19, 24, 26, 27, 31]","[1, 3, 5, 6, 8, 9, 15, 17, 20, 21, 22, 25, 29,...","[0, 4, 7, 11, 12, 23, 28]"
5,"[32, 33, 1, 35, 36, 34, 6, 7, 39, 5, 10, 14, 2...","[4, 37, 9, 11, 12, 13, 16, 17, 19, 20, 25, 26,...","[0, 2, 3, 38, 8, 15, 18, 23, 24]"
6,"[1, 2, 35, 4, 34, 6, 38, 3, 9, 37, 36, 15, 17,...","[0, 5, 7, 10, 11, 12, 13, 14, 16, 19, 20, 21, ...",[8]
7,"[1, 4, 5, 6, 7, 9, 10, 18, 19, 20, 23, 29, 30,...","[0, 2, 8, 11, 12, 14, 16, 17, 21, 22, 24, 25, ...","[3, 13, 15]"
8,"[32, 1, 34, 35, 4, 2, 0, 3, 8, 5, 7, 11, 33, 1...","[36, 37, 38, 9, 16, 17, 19, 22, 23, 24, 26, 28...","[6, 39, 10, 12, 13, 14, 15, 25, 27]"
9,"[33, 1, 3, 36, 5, 38, 37, 35, 2, 10, 11, 12, 3...","[0, 32, 8, 9, 15, 18, 20, 21, 24, 25, 28]","[4, 6, 39, 7, 17, 19, 22, 23, 26]"
10,"[32, 0, 34, 35, 36, 5, 38, 39, 8, 9, 4, 10, 37...","[2, 7, 11, 12, 14, 15, 16, 17, 19, 21, 22, 23,...","[18, 29, 13]"
11,"[32, 34, 2, 36, 4, 5, 7, 8, 37, 38, 3, 35, 26,...","[0, 1, 6, 9, 10, 11, 12, 14, 15, 16, 17, 18, 1...","[33, 29, 13]"
12,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 14, 18,...","[15, 16, 21, 22, 27]","[10, 13, 17, 20, 23, 24, 25, 26]"
13,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 17, 18,...","[11, 14, 15, 23, 25]","[16, 21, 13]"
14,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 18, 19, 20, 22,...","[10, 11, 12, 13, 14, 15, 16, 17, 21, 24, 25, 2...",[]
15,"[0, 33, 34, 4, 37, 39, 23, 28, 29, 31]","[32, 1, 3, 6, 11, 12, 13, 14, 15, 16, 17, 18, ...","[2, 35, 36, 5, 38, 7, 8, 9, 10, 19, 24, 27]"
16,"[0, 33, 2, 3, 36, 37, 38, 4, 9, 13, 14, 16, 17...","[32, 34, 35, 5, 6, 7, 8, 39, 10, 11, 12, 15, 1...",[1]
17,"[0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 13, 18, 29...","[11, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 2...","[28, 7]"
18,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 14, 16, 18,...","[32, 33, 37, 38, 11, 12, 13, 15, 17, 20, 21, 2...",[]
19,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 17,...","[13, 14, 15, 16, 20, 22, 23, 24, 25, 26, 27, 29]","[21, 38]"
20,"[3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 17, 18, ...","[0, 2, 39, 15, 25, 26, 27]","[1, 12, 16, 20, 23, 24]"
21,"[1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 1...","[0, 33, 34, 2, 11, 16, 20, 25]",[30]
22,"[1, 2, 3, 4, 8, 9, 10, 13, 17, 18, 23, 26, 28,...","[0, 5, 39, 11, 14, 15, 16, 21, 25, 27, 30]","[6, 7, 12, 19, 20, 22, 24]"
23,"[0, 1, 33, 3, 4, 6, 13, 31]","[2, 9, 11, 14, 15, 16, 19, 20, 21, 22, 23, 24,...","[5, 7, 8, 10, 12, 17, 18, 25]"
24,"[0, 1, 2, 3, 4, 5, 6, 12, 13, 16, 17, 19, 20, ...","[32, 39, 11, 14, 15]","[33, 35, 7, 8, 9, 10, 18, 26]"
25,"[0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 17, 1...","[33, 3, 4, 15, 23, 25, 26, 27, 29]","[39, 14, 16, 20, 24]"
26,"[0, 1, 2, 3, 5, 6, 7, 8, 10, 13, 18, 19]","[32, 34, 35, 4, 36, 38, 39, 37, 9, 12, 15, 17,...","[33, 11, 14, 16, 21, 23, 27, 28]"
27,"[1, 2, 35, 3, 7, 8, 12, 13, 15, 16, 17, 20, 22...","[32, 33, 34, 4, 38, 39, 14, 18, 24, 25, 26, 27]","[0, 36, 5, 37, 6, 9, 10, 11, 19, 21, 28, 31]"
28,"[0, 33, 1, 3, 4, 5, 37, 39, 6, 32, 34, 2, 9, 1...","[35, 38, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20...","[8, 36]"
29,"[1, 2, 3, 4, 5, 6, 8, 9, 10, 18, 19, 23, 26, 2...","[37, 11, 12, 14, 15, 16, 20, 21, 22, 24, 25, 2...","[0, 36, 7, 13, 17]"
30,"[33, 1, 2, 4, 5, 3, 7, 8, 10, 16, 18, 19, 26, 29]","[32, 35, 36, 6, 38, 39, 11, 14, 20, 21, 22, 24...","[0, 34, 37, 9, 12, 13, 15, 17, 23, 27, 28]"
31,"[32, 33, 0, 35, 36, 34, 38, 39, 37, 9, 1, 18, ...","[3, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 19, ...","[2, 4, 5, 6, 30]"
32,"[2, 4, 7, 9, 10, 13, 15, 17, 18, 20, 21, 22, 2...","[32, 1, 5, 6, 39, 8, 11, 12, 14, 19, 25]","[16, 27, 3, 0]"

In [60]:
high_nb = [ len(trial_list) for trial_list in high]
low_nb = [ len(trial_list) for trial_list in low]
none_nb= [ len(trial_list) for trial_list in none]

In [61]:
df_nb = pd.DataFrame(list(zip(high_nb, low_nb, none_nb)), columns =['High', 'Low', 'None'])

In [62]:
df_nb

    High  Low  None
0      0    0     0
1     24   15     1
2     21   13     6
3      7   32     1
4     11   22     7
5     16   15     9
6     16   23     1
7     22   15     3
8     18   13     9
9     20   11     9
10    20   17     3
11    14   23     3
12    27    5     8
13    32    5     3
14    27   13     0
15    10   18    12
16    19   20     1
17    24   14     2
18    25   15     0
19    26   12     2
20    27    7     6
21    31    8     1
22    22   11     7
23     8   24     8
24    27    5     8
25    26    9     5
26    12   20     8
27    16   12    12
28    18   20     2
29    22   13     5
30    14   15    11
31    16   19     5
32    25   11     4

In [63]:
os.chdir('/home/shreya/DEAP/CNN')
df_nb.to_csv('TA.csv')